owner: quickrstudio
repo: upptime

sites:
  - name: Astro
    url: https://astro.quickr.studio
  - name: Node 1
    url: $NODE1_URL
  - name: Node 2
    url: $NODE2_URL

status-website:
  cname: status.quickr.studio
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Quickr Studio
  introTitle: "Together working for a technological world."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
