owner: quickrstudio
repo: upptime

sites:
  - name: Astro Dashboard
    url: https://astro.quickr.studio
  - name: Node 1
    url: $NODE1_URL
    expectedStatusCodes:
      - 401
  - name: Node 2
    url: $NODE2_URL
    expectedStatusCodes:
      - 401

status-website:
  cname: status.quickr.studio
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Quickr Studio
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
